[package]
name = "qrcode_login"
version = "0.1.0"
edition = "2021"

[dependencies]
ricq = { path = "../../ricq" }
tokio = "1"
serde_json = "1"
bytes = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
